-- Create DOCUMENTS table
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
    TENANT_NAME VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    FILE_SIZE INT NOT NULL,
    TOTAL_CHUNKS INT NOT NULL,
    STATUS ENUM('processing', 'ready', 'failed') DEFAULT 'processing',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_TENANT (TENANT_NAME),
    INDEX IDX_USER (USER_ID),
    INDEX IDX_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create CHAT_HISTORY table
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    CHAT_ID VARCHAR(50) PRIMARY KEY,
    TENANT_NAME VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT NOT NULL,
    SOURCES JSON,
    MODEL VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_TENANT (TENANT_NAME),
    INDEX IDX_USER (USER_ID),
    INDEX IDX_CREATED (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
